MvcProjeKampi/Controllers/OturumController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramewoek;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.DotNet.Scaffolding.Shared.Project;
using MvcProjeKampi.ViewModels;
using System.Reflection.Metadata.Ecma335;
using ValidationResult = FluentValidation.Results.ValidationResult;
namespace MvcProjeKampi.Controllers
{
    public class OturumController : Controller
    {
        

        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        public OturumController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult UyeOl()
        {
            return View();
        }
        //KullaniciManager kullaniciManager=new KullaniciManager(new EfKullaniciDal());
        [HttpPost]
        public async Task<IActionResult> UyeOl(UserSingUpViewModel userSingUpView)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            AppUser appUser = new AppUser()
            {
                Ad = userSingUpView.Ad,
                Soyad = userSingUpView.Soyad,
                Cinsiyet = userSingUpView.Cinsiyet,
                PhoneNumber = userSingUpView.PhoneNumber,
                Email = userSingUpView.Email,
                UserName = userSingUpView.UserName,
                Age = userSingUpView.Age
            };
            var result = await _userManager.CreateAsync(appUser, userSingUpView.Password);
            if (result.Succeeded)
            {
                ViewBag.ms = "Kayıt olma işlemi başarıyla gerçekleşti";
            }
            foreach (IdentityError item in result.Errors)
            {
                ModelState.AddModelError(string.Empty, item.Description);
            }
            return View();
        }
        public IActionResult GirisYap()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GirisYap(LoginViewModel loginViewModel,string? returnUrl=null)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            returnUrl = returnUrl ?? Url.Action("Index", "HomePage");

            var hasUser = await _userManager.FindByEmailAsync(loginViewModel.Email);
            if(hasUser == null)
            {
                ViewBag.msj = "E-Posta veya Şifre Yanlış.";
                return View();
            }
            var result = await _signInManager.PasswordSignInAsync(hasUser, loginViewModel.Password, false, false);
            if (result.Succeeded)
            {
                return Redirect(returnUrl!);
            }
            ViewBag.msj = "E-Posta veya Şifre Yanlış.";
            return View();
        }

        public async Task LogOut()
        {
            await _signInManager.SignOutAsync();
        }

        [Authorize]
        public async Task<IActionResult> Profil()
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name!);

            var userViewModel = new UserViewModel()
            {
                Id = currentUser.Id,
                Ad = currentUser.Ad,
                Soyad = currentUser.Soyad,
                Cinsiyet = currentUser.Cinsiyet,
                Age = currentUser.Age,
                UserName = currentUser.UserName,
                Email = currentUser.Email,
                PasswordHash = currentUser.PasswordHash
            };
            return View(userViewModel);

        }

        [Authorize]
        public IActionResult PasswordChange()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PasswordChange(PasswordChangeViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            var hasUser = await _userManager.FindByNameAsync(User.Identity!.Name!);

            var checkOldPass=await _userManager.CheckPasswordAsync(hasUser, model.OldPassword);

            if(!checkOldPass)
            {
                ViewBag.err = "Eski Şifreniz Yanlış";
                return View();
            }
            if(model.OldPassword == model.NewPassword)
            {
                ViewBag.err = "Eski Şifreniz ile Yeni Şifre Aynı Olamaz";
                return View();
            }
            var resultChangePass= await _userManager.ChangePasswordAsync(hasUser,model.OldPassword,model.NewPassword);

            ViewBag.ok = "Şifre Güncellendi";

            return View();
        }

        [Authorize]
        public async Task<IActionResult> EditUser()
        {
            var hasUser = await _userManager.FindByNameAsync(User.Identity!.Name!);

            var userEditViewModel = new UserEditViewModel()
            {
                Id = hasUser.Id,
                Ad = hasUser.Ad,
                Soyad = hasUser.Soyad,
                Age = hasUser.Age,
                Cinsiyet = hasUser.Cinsiyet,
                UserName = hasUser.UserName,
                Email = hasUser.Email,
            };
            return View(userEditViewModel);

        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditUser(UserEditViewModel userEditViewModel)
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name!);

            currentUser.Ad= userEditViewModel.Ad;
            currentUser.Soyad= userEditViewModel.Soyad;
            currentUser.Age= userEditViewModel.Age;
            currentUser.Cinsiyet= userEditViewModel.Cinsiyet;
            currentUser.UserName= userEditViewModel.UserName;
            currentUser.Email= userEditViewModel.Email;

            var updateUser= await _userManager.UpdateAsync(currentUser);
            if(updateUser.Succeeded)
            {
                ViewBag.ok = "Güncelleme İşlemi Başarılı";
            }
            return View();
        }
    }
}

MvcProjeKampi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcProjeKampi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcProjeKampi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcProjeKampi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcProjeKampi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcProjeKampi/Views/Shared/_NavbarLogin.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if(User.Identity!.IsAuthenticated)
{
    <li class="tm-nav-item">
        <a href="/Oturum/Profil" class="tm-nav-link">
            Bilgilerim
        </a>
    </li>
    <li class="tm-nav-item">
        <a class="tm-nav-link" asp-action="LogOut" asp-controller="Oturum" asp-route-returnUrl="/HomePage/Index">
            Çıkış Yap
        </a>
    </li>
}
else
{
    <li class="tm-nav-item">
        <a href="/Oturum/UyeOl" class="tm-nav-link">
          Üye Ol
        </a>
    </li>
    <li class="tm-nav-item">
        <a href="/Oturum/GirisYap" class="tm-nav-link">
          Giriş Yap
        </a>
    </li>
}

MvcProjeKampi/Views/Shared/_NavbarLoginName.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if(User.Identity!.IsAuthenticated)
{
    <p class="display-5" style="color:aliceblue; text-align:center;">HOŞGELDİNİZ <br> @User.Identity.Name</p>
}

MvcProjeKampi/Views/Shared/_ProjeLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_ProjeLayout</title>
    <script src="/js/jquery.min.js"></script>
    <script src="/js/templatemo-script.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Xtra Blog</title>
    <link rel="stylesheet" href="/fontawesome/css/all.min.css"> <!-- https://fontawesome.com/ -->
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"> <!-- https://fonts.google.com/ -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/templatemo-xtra-blog.css" rel="stylesheet">
    <script src="/js/jquery.min.js/web"></script>
    <script src="/js/responsiveslides.min.js"></script>
    <style>
    </style>
</head>
<body>
    <header class="tm-header" id="tm-header">
        <div class="tm-header-wrapper">
            <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="tm-site-header">
                <div class="mb-3 mx-auto tm-site-logo"><i class="fas fa-times fa-2x"></i></div>
                <h1 class="text-center">Mis Meal</h1>
                <partial name="_NavbarLoginName">
            </div>
            <nav class="tm-nav" id="tm-nav">
                <ul>
                    <li class="tm-nav-item active">
                        <a href="/HomePage/Index" class="tm-nav-link">
                            
                            Ana Sayfa
                        </a>
                    </li>
                    <li class="tm-nav-item">
                        <a href="/Tarifler/Index" class="tm-nav-link">
                            
                            Tarifler
                        </a>
                    </li>
                    <li class="tm-nav-item">
                        <a href="/About/Index" class="tm-nav-link">
                            
                            Hakkımızda
                        </a>
                    </li>
                    <li class="tm-nav-item">
                        <a href="/Contact/Index" class="tm-nav-link">
                            
                            İletişim
                        </a>
                    </li>
                    <partial name="_NavbarLogin">

                </ul>
            </nav>
            <div class="tm-mb-65">
                <a rel="nofollow" href="https://fb.com/templatemo" class="tm-social-link">
                    <i class="fab fa-facebook tm-social-icon"></i>
                </a>
                <a href="https://twitter.com" class="tm-social-link">
                    <i class="fab fa-twitter tm-social-icon"></i>
                </a>
                <a href="https://instagram.com" class="tm-social-link">
                    <i class="fab fa-instagram tm-social-icon"></i>
                </a>
                <a href="https://linkedin.com" class="tm-social-link">
                    <i class="fab fa-linkedin tm-social-icon"></i>
                </a>
            </div>
            @*<p class="tm-mb-80 pr-5 text-white">
                Xtra Blog is a multi-purpose HTML template from TemplateMo website. Left side is a sticky menu bar. Right side content will scroll up and down.
            </p>*@
        </div>
    </header>
    <div>
        @RenderBody()
    </div>
    <footer class="row tm-row">
        <hr class="col-12">
        <div class="col-md-6 col-12 tm-color-gray">
            Design: <a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-external-link">TemplateMo</a>
        </div>
        <div class="col-md-6 col-12 tm-color-gray tm-copyright">
            Copyright 2020 Xtra Blog Company Co. Ltd.
        </div>
    </footer>
</body>
</html>